worker_processes 1;

events { worker_connections 1024; }

http {
    include mime.types;
    sendfile on;

    server {
        listen 80;

        # Servir os arquivos estáticos do frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Proxy reverso para auth-service
        location /api/auth/ {
            proxy_pass http://auth-service:8081;
        }
        location /api/users/ {
            proxy_pass http://auth-service:8081;
        }
        location /api/users {
            proxy_pass http://auth-service:8081;
        }

        # Proxy reverso para catalog-service
        location /api/clients/ {
            proxy_pass http://catalog-service:8082;
        }
        location /api/clients {
            proxy_pass http://catalog-service:8082;
        }
        location /api/products/ {
            proxy_pass http://catalog-service:8082;
        }
        location /api/products {
            proxy_pass http://catalog-service:8082;
        }
    }
}
