version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - catalog-service

  auth-service:
    build: ./auth-service
    expose:
      - "8081"
    environment:
      - MONGODB_URI=mongodb+srv://MatheusRP:UcRVj6GjUtHmMOWx@cluster0.df3drqo.mongodb.net/savir-sistemas-java?retryWrites=true&w=majority&appName=Cluster0

  catalog-service:
    build: ./catalog-service
    expose:
      - "8082"
    environment:
      - MONGODB_URI=mongodb+srv://MatheusRP:UcRVj6GjUtHmMOWx@cluster0.df3drqo.mongodb.net/savir-sistemas-java?retryWrites=true&w=majority&appName=Cluster0
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - auth-service
